"""Short hover explanations, keyed by the visible text of a button, switch or check box."""
TIPS = {
    "Advanced": "Shows the expert controls. Leave it off to keep only the everyday ones.",
    "Apply": "Uses the selected preset now.",
    "Save as...": "Stores the current settings under a name of your choice.",
    "Enable the equalizer": "Adds a ten-band equalizer with presets. Restarts the sound server for a second or two.",
    "Turn the equalizer off": "Removes the equalizer; the plain volume and the speaker boost stay.",
    "Verify the settings are applied": "Reads the sound server back and checks that what you set is really active.",
    "Enable the microphone enhancer": "Adds a gain stage and a small equalizer on top of the built-in noise suppression.",
    "Turn the enhancer off": "Goes back to the plain microphone.",
    "Left": "Plays a short sound in the left speaker only. If it comes from the right, the channels are swapped.",
    "Right": "Plays a short sound in the right speaker only.",
    "Both": "Plays a short stereo melody that bounces from left to right, then a chord with different notes in each speaker.",
    "Sweep": "Slowly glides from very low to very high pitch, to hear rattles, gaps or a weak range.",
    "Record 6 seconds": "Records the microphone for six seconds with the current settings.",
    "Play back": "Plays the recording, to hear what the other side of a call hears.",
    "Stop": "Stops the current test.",
    "Same equalizer for speakers and headphones": "One profile for both ports. Clear it to keep a separate profile for the speakers and the headphones.",
    "Hold the volume keys to repeat": "When on, holding a volume button keeps changing the volume. Turn it off for one step per press.",
    "Import file...": "Loads an Equalizer APO or AutoEQ text file.",
    "Export...": "Saves the current curve as an Equalizer APO text file.",
    "Reset to flat": "Sets all bands to zero.",
    "On": "Switches this band on or off.",
    "Back": "Returns to the previous page.",
    "Check again": "Runs all the checks again.",
    "Clear": "Erases what is shown.",
    "Restart now": "Restarts the computer.",
    "Restart camera service": "Restarts the camera daemon. Open camera apps must be reopened.",
    "Re-detect keyboard and trackpad": "Same as unplugging and attaching the cover again. Takes about 5 seconds.",
    "Rebuild drivers and camera library...": "Rebuilds the four patched drivers for the running kernel. Needed after a kernel update.",
    "Exit test": "Leaves the keyboard test and brings the shortcuts back.",
    "Reset": "Marks all keys as untested.",
    "Start the test": "Starts the test.",
    "Hide the fake stylus battery": "Hides the pen battery the touchscreen advertises without data. Needs a restart.",
    "Mirror (left-right)": "Flips the picture horizontally, like a mirror.",
    "Flip (upside-down)": "Turns the picture upside down.",
    "Front camera": "Selects the front camera (selfie).",
    "Rear camera": "Selects the rear camera (with autofocus).",
    "Reset all adjustments to the tuned defaults": "Puts every slider back to the recommended value.",
    "Delete...": "Deletes this preset.",
    "Rename...": "Changes the name of this preset.",
    "Duplicate...": "Makes a copy of this preset.",
    "Update with the current settings...": "Replaces this preset with the settings in use.",
    "Show the fake stylus battery": "Shows the pen battery the touchscreen advertises again.",
}
